version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bath-postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '6500:5432'
  redis:
    image: redis:alpine
    container_name: bath-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
  redis: